# Generated by Django 6.0.6 on 2026-06-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='stock_symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='TriggeredAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_alerts.alertrule')),
            ],
        ),
    ]
